config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :massmails do
     
     collection do
       get :mysender
       post :sendengine
       get :myletter
       post :letterengine
     end 
  end 
  root 'massmails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/massmail.rb
class Massmail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/massmails_controller.rb
class MassmailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_massmail, only: [:show, :edit, :update, :destroy]

  # GET /massmails
  # GET /massmails.json
  def index
    @massmails = Massmail.all
  end

  def mysender
    
  end  
  def sendengine
    @riends = params[:email]
    friends = @riends.split
    #num = 0
    toreply = params[:toreply]
    data = params[:body]
    subject = params[:subject]
    greeting = params[:greeting]
    sender_name = params[:sender_name]
    sender = params[:sender_email]
    imagepath = params[:imagepath]
    linkpath = params[:linkpath]
    #friends = @friends.map(&:to_s)
     #@friends.each_line do |friend|
       #num += 1
      
      #LoanMailer.welcome(friend,toreply,data,subject,greeting,sender_name,sender).deliver
      SendLoanEmailJob.set(wait: 40.seconds).perform_later(friends,toreply,data,subject,greeting,sender_name,sender)
    
    redirect_to root_path
  end  
  # GET /massmails/1
  # GET /massmails/1.json
  def myletter
    
  end  
  def letterengine
    @riends = params[:email]
    friends = @riends.split
    #num = 0
    toreply = params[:toreply]
    data = params[:body]
    subject = params[:subject]
    greeting = params[:greeting]
    sender_name = params[:sender_name]
    sender = params[:sender_email]
    imagepath = params[:imagepath]
    linkpath = params[:linkpath]
    friends.each do |friend| 
      #SendLetterEmailJob.set(cron: '*/1 * * * *').perform_later(friend,toreply,data,subject,greeting,sender_name,sender)
      SendLetterEmailJob.set(wait: 40.seconds).perform_later(friend,toreply,data,subject,greeting,sender_name,sender)
    end
    #SendLetterEmailJob.set(cron: '*/1 * * * * RAILS_ENV=production bundle exec rake jobs:workoff').perform_later
    redirect_to root_path
  end 
  def show
  end

  # GET /massmails/new
  def new
    @massmail = Massmail.new
  end

  # GET /massmails/1/edit
  def edit
  end

  # POST /massmails
  # POST /massmails.json
  def create
    @massmail = Massmail.new(massmail_params)

    respond_to do |format|
      if @massmail.save
        format.html { redirect_to @massmail, notice: 'Massmail was successfully created.' }
        format.json { render :show, status: :created, location: @massmail }
      else
        format.html { render :new }
        format.json { render json: @massmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /massmails/1
  # PATCH/PUT /massmails/1.json
  def update
    respond_to do |format|
      if @massmail.update(massmail_params)
        format.html { redirect_to @massmail, notice: 'Massmail was successfully updated.' }
        format.json { render :show, status: :ok, location: @massmail }
      else
        format.html { render :edit }
        format.json { render json: @massmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /massmails/1
  # DELETE /massmails/1.json
  def destroy
    @massmail.destroy
    respond_to do |format|
      format.html { redirect_to massmails_url, notice: 'Massmail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_massmail
      @massmail = Massmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def massmail_params
      params.fetch(:massmail, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/massmails_helper.rb
module MassmailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<header>
  <% if user_signed_in? %>
    <div class="nav_item">
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
       |
      <%= link_to "Send Mails", mysender_massmails_path, class: "btn btn-info" %>
       |
      <%= link_to "Free Form", myletter_massmails_path, class: "btn btn-info" %> 
    </div>
  <% end %>
</header>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/massmails/_form.html.erb
<%= form_for(@massmail) do |f| %>
  <% if @massmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@massmail.errors.count, "error") %> prohibited this massmail from being saved:</h2>

      <ul>
      <% @massmail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/massmails/edit.html.erb
<h1>Editing Massmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @massmail %> |
<%= link_to 'Back', massmails_path %>

app/views/massmails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Massmails</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @massmails.each do |massmail| %>
      <tr>
        <td><%= link_to 'Show', massmail %></td>
        <td><%= link_to 'Edit', edit_massmail_path(massmail) %></td>
        <td><%= link_to 'Destroy', massmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Massmail', new_massmail_path %>

app/views/massmails/myletter.html.erb
<%= bootstrap_form_tag url: '/massmails/letterengine' do |f| %>
<div class="row">
<div class="col-md-6 form-group">
<%= f.text_area 'email', hide_label: true, placeholder: "Load emails per line...", cols: "10", rows: "20"%></br>
</div>
<div class="col-md-6">
<%= f.form_group do %>
<div class="row">
 <div class="col-md-4">
   <%= f.text_field 'sender_name', hide_label: true,placeholder: "Sender name"%>
 </div>
 <div class="col-md-4">
   <%= f.text_field 'sender_email', hide_label: true,placeholder: "Sender Email"%>
 </div>
  <div class="col-md-4">
   <%= f.text_field 'toreply', hide_label: true,placeholder: "Reply To Email"%>
 </div>
</div>
<div class="row">
 <div class="col-md-6">
   <%= f.text_field 'imagepath', hide_label: true,placeholder: "Picture url for inline pic"%>
 </div>
  <div class="col-md-6">
   <%= f.text_field 'linkpath', hide_label: true,placeholder: "Link url for clike"%>
 </div>
</div>
<div class="row">
 <div class="col-md-6">
   <%= f.text_field 'subject', hide_label: true,placeholder: "Subject"%>
 </div>
  <div class="col-md-6">
   <%= f.text_field 'greeting', hide_label: true,placeholder: "Greeting"%>
 </div>
</div>

<%= f.text_area 'body', hide_label: true,placeholder: "Leave a comment...", cols: "20", rows: "10"%>
<%= submit_tag "submit",:value => "submit"%>
<%end%>
</div>
</div>
<%end%>

app/views/massmails/mysender.html.erb
<%= bootstrap_form_tag url: '/massmails/sendengine' do |f| %>
<div class="row">
<div class="col-md-6 form-group">
<%= f.text_area 'email', hide_label: true, placeholder: "Load emails per line...", cols: "10", rows: "20"%></br>
</div>
<div class="col-md-6">
<%= f.form_group do %>
<div class="row">
 <div class="col-md-4">
   <%= f.text_field 'sender_name', hide_label: true,placeholder: "Sender name"%>
 </div>
 <div class="col-md-4">
   <%= f.text_field 'sender_email', hide_label: true,placeholder: "Sender Email"%>
 </div>
  <div class="col-md-4">
   <%= f.text_field 'toreply', hide_label: true,placeholder: "Reply To Email"%>
 </div>
</div>
<div class="row">
 <div class="col-md-6">
   <%= f.text_field 'imagepath', hide_label: true,placeholder: "Picture url for inline pic"%>
 </div>
  <div class="col-md-6">
   <%= f.text_field 'linkpath', hide_label: true,placeholder: "Link url for clike"%>
 </div>
</div>
<div class="row">
 <div class="col-md-6">
   <%= f.text_field 'subject', hide_label: true,placeholder: "Subject"%>
 </div>
  <div class="col-md-6">
   <%= f.text_field 'greeting', hide_label: true,placeholder: "Greeting"%>
 </div>
</div>

<%= f.text_area 'body', hide_label: true,placeholder: "Leave a comment...", cols: "20", rows: "10"%>
<%= submit_tag "submit",:value => "submit"%>
<%end%>
</div>
</div>
<%end%>

app/views/massmails/new.html.erb
<h1>New Massmail</h1>

<%= render 'form' %>

<%= link_to 'Back', massmails_path %>

app/views/massmails/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_massmail_path(@massmail) %> |
<%= link_to 'Back', massmails_path %>